spring:
  mail:
    to: 1162220289@qq.com
    host: smtp.qq.com
    port: 587
    username: authcenter@qq.com
    password: wwavczflxggijaie
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
file:
  location:
    3d: D:\彩票\3D.xlsx
    compare3D: D:\彩票\3D对比.xlsx
    pl3: D:\彩票\排列三.xlsx
    comparePl3: D:\彩票\排列三对比.xlsx
server:
  port: 10088